languageCode = "en-US"
title = "Munin Plugin Gallery"
theme = "ace-documentation"

MetaDataFormat = "yaml"
enableRobotsTXT = true
rssLimit = 200

[outputs]
  # enable JSON output for "search" via lunr (see index.json)
  home = [ "HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true

[minify]
  minifyOutput = true

[params]
  site_logo = "/logo.svg"
  description = "Collection of all plugins maintained by the Munin developers"
  # disable the navigation footer provided by ace-documentation
  disableReadmoreNav = true

[taxonomies]
  capability = "capabilities"
  category = "categories"
  family = "families"
  implementation_language = "implementation_languages"
  keyword = "keywords"
  repository = "repositories"
  author = "authors"
  license = "licenses"
  missing_detail = "missing_details"


[[menu.shortcuts]]
  name = "Contribute"
  url = "/contribute/"
  weight = 10

[[menu.shortcuts]]
  name = "Categories"
  url = "/categories/"
  weight = 30

[[menu.shortcuts]]
  name = "Keywords"
  url = "/keywords/"
  weight = 40

[[menu.shortcuts]]
  name = "Authors"
  url = "/authors/"
  weight = 50

[[menu.shortcuts]]
  name = "Sources"
  url = "/repositories/"
  weight = 80


[module]
  [[module.mounts]]
    source = "../build/plugins"
    target = "content/plugins"

  [[module.mounts]]
    source = "content"
    target = "content"
